name: Publish Chrome Extension

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Zip the extension
        run: zip -r build.zip * -x .git .github
      - name: List after zipping
        run: |
          echo "All files and directories (including hidden):"
          find . -not -path '*/\.*'
      - name: Verify ZIP file
        run: |
          if [ -f "build.zip" ]; then
            echo "build.zip exists"
          else
            echo "build.zip does not exist"
            exit 1
          fi
#      - name: Create ZIP file
#        run: zip -r build.zip . -x "*.git*" "node_modules/*" "package-lock.json" ls -l build.zip
#      - name: Zip the extension
#        run: zip -r my-extension.zip path/to/extension
#      - name: Publish to Chrome Web Store
#        uses: redromnon/chrome-webstore-publish@v1.1.0
#        with:
#          extension_id: ${{ secrets.CHROME_EXTENSION_ID }}
#          client_id: ${{ secrets.CHROME_CLIENT_ID }}
#          client_secret: ${{ secrets.CHROME_CLIENT_SECRET }}
#          refresh_token: ${{ secrets.CHROME_REFRESH_TOKEN }}
#          zip: ./my-extension.zip
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Chrome Web Store
        uses: trmcnvn/chrome-addon@v2
        with:
          extension: ${{ secrets.CHROME_EXTENSION_ID }}
          zip: /home/runner/work/auto-congrats/auto-congrats/build.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
#      - uses: actions/checkout@v3
#      - name: Upload to Chrome Web Store
#        uses: trmcnvn/chrome-addon@v2
#        with:
#          extension: ${{ secrets.CHROME_EXTENSION_ID }}
#          zip: /home/runner/work/auto-congrats/auto-congrats/build.zip
#          client-id: ${{ secrets.CHROME_CLIENT_ID }}
#          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
#          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}